"""AskMyDocs web UI + API: semantic search and grounded Q&A over the catalog.

Run:
    uv run python -m serve            # http://localhost:8008

Endpoints:
    GET  /                  — single-page UI
    POST /api/search        — {query, top_k} -> ranked tables
    POST /api/ask           — {question, top_k} -> grounded answer + sources
    GET  /api/table/{name}  — full text blob for one table
    GET  /api/health        — corpus size, model info

The embeddings Parquet is loaded once at startup (pyarrow + numpy — no Spark
in the serving path). Answers are generated by Gemini strictly from the
retrieved context; if the context doesn't cover the question, it must say so.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import numpy as np
from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse
from pydantic import BaseModel, Field

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from serve import matching  # noqa: E402
from spark_jobs.embeddings_core import (  # noqa: E402
    cosine_top_k,
    l2_normalize,
    resolve_gemini_api_key,
)

EMBEDDINGS_DIR = Path(os.environ.get(
    "ASKMYDOCS_EMBEDDINGS_OUT", REPO / "data" / "parquet" / "embeddings"))
# gemini-flash-latest tracks the current flash generation — pinned models
# (e.g. gemini-2.5-flash) get closed to new accounts as generations roll.
ANSWER_MODEL = os.environ.get("ASKMYDOCS_ANSWER_MODEL", "gemini-flash-latest")
INDEX_HTML = (Path(__file__).parent / "index.html").read_text(encoding="utf-8")

app = FastAPI(title="AskMyDocs")

# Allow the UI to call the API when index.html is opened directly from disk
# (origin "null") instead of being served by us. Local tool — permissive is fine.
from fastapi.middleware.cors import CORSMiddleware  # noqa: E402

app.add_middleware(
    CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

# --- corpus, loaded once at startup -----------------------------------------

class Corpus:
    names: list[str]
    domains: list[str]
    blobs: list[str]
    matrix: np.ndarray
    model: str
    dims: int

    def __init__(self) -> None:
        import pyarrow.parquet as pq

        if not EMBEDDINGS_DIR.exists():
            raise SystemExit(
                f"{EMBEDDINGS_DIR} not found — run: python -m spark_jobs build_embeddings")
        t = pq.read_table(EMBEDDINGS_DIR)
        if t.num_rows == 0:
            raise SystemExit(f"{EMBEDDINGS_DIR} is empty — rebuild embeddings")
        self.names = t["table_name"].to_pylist()
        self.domains = t["business_domain"].to_pylist()
        self.blobs = t["text_blob"].to_pylist()
        self.matrix = np.asarray(t["embedding"].to_pylist(), dtype=np.float32)
        self.model = t["embedding_model"][0].as_py()
        self.dims = t["embedding_dims"][0].as_py()
        self.by_name = {n: i for i, n in enumerate(self.names)}


CORPUS = Corpus()


_CLIENT = None


def gemini_client():
    """One shared client for the process. A per-request temporary gets
    garbage-collected mid-call (its finalizer closes the httpx client),
    yielding 'Cannot send a request, as the client has been closed'."""
    global _CLIENT
    if _CLIENT is None:
        from google import genai

        api_key = resolve_gemini_api_key()
        if not api_key:
            raise HTTPException(503, "GEMINI_API_KEY not set (env or .env)")
        _CLIENT = genai.Client(api_key=api_key)
    return _CLIENT


def embed_query(text: str) -> list[float]:
    from google.genai import types

    resp = gemini_client().models.embed_content(
        model=CORPUS.model,
        contents=text,
        config=types.EmbedContentConfig(
            task_type="RETRIEVAL_QUERY", output_dimensionality=CORPUS.dims),
    )
    return l2_normalize(list(resp.embeddings[0].values))


def purpose_of(blob: str, max_len: int = 300) -> str:
    for section in blob.split("\n\n"):
        if section.startswith("Purpose:"):
            text = section[len("Purpose:"):].strip().replace("\n", " ")
            return text if len(text) <= max_len else text[: max_len - 1] + "…"
    return blob[:max_len]


def retrieve(query: str, top_k: int) -> list[dict]:
    # Semantic embeddings are unreliable for exact identifiers, so a question
    # like "explain orders_base_007" must deterministically include that entry.
    pinned = matching.exact_mentions(query, CORPUS.by_name)
    hits = cosine_top_k(embed_query(query), CORPUS.matrix, top_k)
    # pinned exact-name matches first, then semantic hits (deduped), cap top_k
    ordered = pinned + [i for i, _ in hits if i not in pinned]
    scores = {i: s for i, s in hits}
    return [
        {
            "table_name": CORPUS.names[i],
            "business_domain": CORPUS.domains[i],
            "score": scores.get(i, 1.0),  # 1.0 marks an exact name match
            "purpose": purpose_of(CORPUS.blobs[i]),
        }
        for i in ordered[:top_k]
    ]


# --- API ----------------------------------------------------------------------

class SearchRequest(BaseModel):
    query: str = Field(min_length=2)
    top_k: int = Field(default=5, ge=1, le=20)


class AskRequest(BaseModel):
    question: str = Field(min_length=2)
    top_k: int = Field(default=5, ge=1, le=10)


ANSWER_PROMPT = """You are AskMyDocs, an assistant answering questions about a logistics \
data warehouse using ONLY the data dictionary entries provided below.

Rules:
- Ground every claim in the provided entries; cite table names in backticks.
- If the entries don't contain the answer, say exactly what's missing — never invent \
tables, columns, or joins.
- If the question names a specific table and no entry has that exact name, open by \
stating clearly that no table with that name exists in the catalog, then suggest the \
closest entries by name and purpose.
- Prefer concrete guidance: which table to use, its grain, relevant columns, join keys.
- Keep it under 250 words.

Question: {question}

Data dictionary entries:
{context}
"""


@app.get("/", response_class=HTMLResponse)
def index() -> str:
    return INDEX_HTML


@app.get("/api/health")
def health() -> dict:
    return {"tables": len(CORPUS.names), "embedding_model": CORPUS.model,
            "dims": CORPUS.dims, "answer_model": ANSWER_MODEL}


@app.post("/api/search")
def search(req: SearchRequest) -> dict:
    return {
        "query": req.query,
        "results": retrieve(req.query, req.top_k),
        "did_you_mean": matching.did_you_mean(req.query, CORPUS.names, CORPUS.by_name),
    }


@app.post("/api/ask")
def ask(req: AskRequest) -> dict:
    sources = retrieve(req.question, req.top_k)
    suggestions = matching.did_you_mean(req.question, CORPUS.names, CORPUS.by_name)
    context = "\n\n---\n\n".join(
        CORPUS.blobs[CORPUS.by_name[s["table_name"]]] for s in sources)
    prompt = ANSWER_PROMPT.format(question=req.question, context=context)
    if suggestions:
        prompt += (
            "\n\nNote: the question mentions a table name that does not exist in "
            f"the catalog. Closest table names: {', '.join(suggestions)}."
        )
    resp = gemini_client().models.generate_content(
        model=ANSWER_MODEL, contents=prompt)
    return {"question": req.question, "answer": resp.text,
            "sources": sources, "did_you_mean": suggestions}


@app.get("/api/table/{name}")
def table_detail(name: str) -> dict:
    i = CORPUS.by_name.get(name)
    if i is None:
        raise HTTPException(404, f"unknown table: {name}")
    return {"table_name": name, "business_domain": CORPUS.domains[i],
            "text_blob": CORPUS.blobs[i]}
