apiVersion: v1
kind: Secret
metadata:
  name: lab-postgres-secret
  namespace: data-platform-lab
type: Opaque
stringData:
  POSTGRES_USER: lab
  POSTGRES_PASSWORD: lab
  POSTGRES_DB: lab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab-postgres-pvc
  namespace: data-platform-lab
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: lab-postgres
  namespace: data-platform-lab
spec:
  selector:
    app: lab-postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-postgres
  namespace: data-platform-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-postgres
  template:
    metadata:
      labels:
        app: lab-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: lab-postgres-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "lab", "-d", "lab"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "lab", "-d", "lab"]
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: lab-postgres-pvc
